language: python
services:
- docker
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- echo "Test begin!!"
- pytest test/testBPI.py
- pytest test/testBTI.py
addons:
  ssh_known_hosts: 51.15.196.143
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: ssh devel@51.15.196.143 "sh ./deploy.sh"
  on:
    branch: integration
    python: '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_a710b40432a9_key -iv $encrypted_a710b40432a9_iv
  -in deploy_rsa.enc -out deploy_rsa -d
